---
:slug: :saved_search
:depends:
  :mikutter: '0.2'
  :plugin:
  - gui
  - change_account
  - uitranslator
  - skin
  - twitter
:version: '1.2'
:author: toshi_a
:name: 保存した検索
:description: Twitterの保存した検索機能のサポート
